# coding: utf-8

"""
    packetgrid-server-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blitzm_packetgrid_sdk
from blitzm_packetgrid_sdk.api.notifications_api import NotificationsApi  # noqa: E501
from blitzm_packetgrid_sdk.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = blitzm_packetgrid_sdk.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send(self):
        """Test case for send

        """
        pass


if __name__ == '__main__':
    unittest.main()
