# coding: utf-8

"""
    packetgrid-server-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blitzm_packetgrid_sdk
from blitzm_packetgrid_sdk.models.recipient import Recipient  # noqa: E501
from blitzm_packetgrid_sdk.rest import ApiException


class TestRecipient(unittest.TestCase):
    """Recipient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecipient(self):
        """Test Recipient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blitzm_packetgrid_sdk.models.recipient.Recipient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
