# coding: utf-8

"""
    packetgrid-server-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blitzm_packetgrid_sdk
from blitzm_packetgrid_sdk.models.notification import Notification  # noqa: E501
from blitzm_packetgrid_sdk.rest import ApiException


class TestNotification(unittest.TestCase):
    """Notification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotification(self):
        """Test Notification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blitzm_packetgrid_sdk.models.notification.Notification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
