# coding: utf-8

"""
    packetgrid-server-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blitzm_packetgrid_sdk
from blitzm_packetgrid_sdk.api.client_token_api import ClientTokenApi  # noqa: E501
from blitzm_packetgrid_sdk.rest import ApiException


class TestClientTokenApi(unittest.TestCase):
    """ClientTokenApi unit test stubs"""

    def setUp(self):
        self.api = blitzm_packetgrid_sdk.api.client_token_api.ClientTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client_token(self):
        """Test case for create_client_token

        create a client token for a mobile device. If a duplicated user_id is provided, the server could probably create a new token or return the existig token.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
