# coding: utf-8

"""
    packetgrid-server-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SendNotification(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'title': 'str',
        'detail': 'str',
        'payload': 'object',
        'recipients': 'list[Recipient]',
        'transports': 'list[TransportEnum]'
    }

    attribute_map = {
        'title': 'title',
        'detail': 'detail',
        'payload': 'payload',
        'recipients': 'recipients',
        'transports': 'transports'
    }

    def __init__(self, title=None, detail=None, payload=None, recipients=None, transports=None):  # noqa: E501
        """SendNotification - a model defined in OpenAPI"""  # noqa: E501

        self._title = None
        self._detail = None
        self._payload = None
        self._recipients = None
        self._transports = None
        self.discriminator = None

        self.title = title
        self.detail = detail
        self.payload = payload
        self.recipients = recipients
        self.transports = transports

    @property
    def title(self):
        """Gets the title of this SendNotification.  # noqa: E501


        :return: The title of this SendNotification.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SendNotification.


        :param title: The title of this SendNotification.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def detail(self):
        """Gets the detail of this SendNotification.  # noqa: E501


        :return: The detail of this SendNotification.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this SendNotification.


        :param detail: The detail of this SendNotification.  # noqa: E501
        :type: str
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")  # noqa: E501

        self._detail = detail

    @property
    def payload(self):
        """Gets the payload of this SendNotification.  # noqa: E501


        :return: The payload of this SendNotification.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this SendNotification.


        :param payload: The payload of this SendNotification.  # noqa: E501
        :type: object
        """
        if payload is None:
            raise ValueError("Invalid value for `payload`, must not be `None`")  # noqa: E501

        self._payload = payload

    @property
    def recipients(self):
        """Gets the recipients of this SendNotification.  # noqa: E501


        :return: The recipients of this SendNotification.  # noqa: E501
        :rtype: list[Recipient]
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """Sets the recipients of this SendNotification.


        :param recipients: The recipients of this SendNotification.  # noqa: E501
        :type: list[Recipient]
        """
        if recipients is None:
            raise ValueError("Invalid value for `recipients`, must not be `None`")  # noqa: E501

        self._recipients = recipients

    @property
    def transports(self):
        """Gets the transports of this SendNotification.  # noqa: E501


        :return: The transports of this SendNotification.  # noqa: E501
        :rtype: list[TransportEnum]
        """
        return self._transports

    @transports.setter
    def transports(self, transports):
        """Sets the transports of this SendNotification.


        :param transports: The transports of this SendNotification.  # noqa: E501
        :type: list[TransportEnum]
        """
        if transports is None:
            raise ValueError("Invalid value for `transports`, must not be `None`")  # noqa: E501

        self._transports = transports

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SendNotification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
